[package]
name = "plonky2"
version = "0.1.0"
authors = ["Daniel Lubarov <daniel@lubarov.com>"]
edition = "2018"

[dependencies]
env_logger = "0.8.3"
log = "0.4.14"
num = "0.3"
rayon = "1.5.0"
unroll = "0.1.5"

[profile.release]
opt-level = 3
#lto = "fat"
#codegen-units = 1
