[package]
name = "plonky2"
description = "Recursive SNARKs based on PLONK and FRI"
version = "0.1.0"
authors = ["Polygon Zero <daniel@mirprotocol.org>"]
readme = "README.md"
repository = "https://github.com/mir-protocol/plonky2"
keywords = ["cryptography", "SNARK", "PLONK", "FRI"]
categories = ["cryptography"]
edition = "2021"
default-run = "generate_constants"

[features]
default = ["parallel", "rand", "rand_chacha", "timing", "gate_testing"]
parallel = ["maybe_rayon/parallel"]
rand = ["dep:rand", "plonky2_field/rand"]
gate_testing = ["rand"]
rand_chacha = ["dep:rand_chacha"]
timing = []

[dependencies]
anyhow = "1.0.40"
derivative = { version = "2.2.0", default-features = false, features = ["use_core"] }
itertools = "0.10.0"
keccak-hash = "0.8.0"
log = "0.4.14"
maybe_rayon = { path = "../maybe_rayon" }
num = { version = "0.4", features = [ "rand" ] }
plonky2_field = { path = "../field" }
plonky2_util = { path = "../util" }
rand = { version = "0.8.4", optional = true }
rand_chacha = { version = "0.3.1", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.1"
static_assertions = "1.1.0"
unroll = "0.1.5"

[dev-dependencies]
criterion = "0.3.5"
env_logger = "0.9.0"
num_cpus = "1.13.1"
rand = "0.8.4"
rand_chacha = "0.3.1"
rayon = "1.5.1" 
structopt = "0.3.26"
tynm = "0.1.6"

[target.'cfg(not(target_env = "msvc"))'.dev-dependencies]
jemallocator = "0.3.2"

[[bin]]
name = "generate_constants"
required-features = ["rand", "rand_chacha"]

[[bench]]
name = "field_arithmetic"
harness = false

[[bench]]
name = "ffts"
harness = false

[[bench]]
name = "hashing"
harness = false

[[bench]]
name = "merkle"
harness = false

[[bench]]
name = "transpose"
harness = false

[[bench]]
name = "reverse_index_bits"
harness = false
