[package]
name = "plonky2"
description = "Recursive SNARKs based on PLONK and FRI"
version = "0.1.0"
authors = ["Polygon Zero <daniel@mirprotocol.org>"]
readme = "README.md"
repository = "https://github.com/mir-protocol/plonky2"
keywords = ["cryptography", "SNARK", "PLONK", "FRI"]
categories = ["cryptography"]
edition = "2021"
default-run = "generate_constants"

[features]
default = ["gate_testing", "parallel", "rand_chacha", "std", "timing"]
gate_testing = []
parallel = ["hashbrown/rayon", "maybe_rayon/parallel"]
std = ["anyhow/std", "rand/std"]
timing = ["std"]

[dependencies]
anyhow = { version = "1.0.40", default-features = false }
derivative = { version = "2.2.0", default-features = false, features = ["use_core"] }
hashbrown = { version = "0.12.3", default-features = false, features = ["ahash", "serde"] }
itertools = { version = "0.10.0", default-features = false }
keccak-hash = { version = "0.8.0", default-features = false }
log = { version = "0.4.14", default-features = false }
maybe_rayon = { path = "../maybe_rayon", default-features = false }
num = { version = "0.4", default-features = false, features = ["rand"] }
plonky2_field = { path = "../field", default-features = false }
plonky2_util = { path = "../util", default-features = false }
rand = { version = "0.8.4", default-features = false }
rand_chacha = { version = "0.3.1", optional = true, default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_cbor = { version = "0.11.1", default-features = false }
static_assertions = { version = "1.1.0", default-features = false }
unroll = { version = "0.1.5", default-features = false }

[dev-dependencies]
criterion = "0.3.5"
env_logger = "0.9.0"
num_cpus = "1.13.1"
plonky2 = { path = "." }
rand = "0.8.4"
rand_chacha = "0.3.1"
rayon = "1.5.1" 
structopt = "0.3.26"
tynm = "0.1.6"

[target.'cfg(not(target_env = "msvc"))'.dev-dependencies]
jemallocator = "0.3.2"

[[bin]]
name = "generate_constants"
required-features = ["rand_chacha"]

[[bench]]
name = "field_arithmetic"
harness = false

[[bench]]
name = "ffts"
harness = false

[[bench]]
name = "hashing"
harness = false

[[bench]]
name = "merkle"
harness = false

[[bench]]
name = "transpose"
harness = false

[[bench]]
name = "reverse_index_bits"
harness = false
